apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inflate
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: https://github.com/deverton/argo-rollouts-demo
    path: inflate
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: default

